### ISSUE TITLE
Modpack Permissions

### ISSUE THREAD

**Issue by Yslohr** [Tfarcenim/lootcapacitortooltips#2]
Hi, I was wondering if you could update your curseforge description and/or post explicitly here on GitHub if you would be okay with adding this mod to a public modpack ? If so what would be the requirements ?

**Comment by aaronhowser1** [comment]
Public Domain means you can do pretty much literally anything with it

**Comment by Tfarcenim** [comment]
Yeah it can be included in any pack, curseforge or not.
